version: '3.8'

services:
  nginx:
    image: nginx:1.27.2
    ports:
      - "8080:80"
    depends_on:
      - rag-microservice
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
    depends_on:
      - rag-microservice
    networks:
      - app-network

  rag-microservice:
    build:
      context: ./rag-microservice
    ports:
      - "5000:5000"
    depends_on:
      - zap-microservice
    networks:
      - app-network

  zap-microservice:
    build:
      context: ./zap-microservice
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
