version: '3.8'

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production