version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - scrapper-microservice

  scrapper-microservice:
    build:
      context: ./scrapper-microservice
    ports:
      - "4000:4000"